### ISSUE TITLE
Locate and make available SLOSH rexfile-to-netcdf code

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/comt#13]
Justin Davis wrote code to convert SLOSH native rex file output to CF compliant NetCDF for Testbed 1 (COMT1).  Let's find this code and put it on github so that COMT2 folks can use it.

**Comment by donatellapasqualini** [comment]
Rex2nc works correctly when I use one of the rex files included in the test directory Rich committed. 
When I use one of the rex files included in the SLOSH package or one that I created using SLOSH, in the ReadRexHeader function the code stops with Abort (signal 6). 
I am working on a MacBook Pro with Intel Core processor. The version of SLOSH I am using is dated 1/20/2012. Any idea?
Thank you
