### ISSUE TITLE
Most SELFE results are missing standard_name fields for latitude/longitude

### ISSUE THREAD

**Issue by kknee** [ioos/comt#25]

**Comment by drf5n** [comment]
Which SELFE results are missing the standard names for lat & lon?  

http://comt.sura.org/thredds/dodsC/comt_1_archive_full/inundation_tropical/VIMS_SELFE/Hurricane_Ike_2D_final_run_with_waves/00_dir.ncml.html appears to have them.

When we pushed the files into the system, we used NCML to aggregate the latitude and longitude coordinate variables with the others, as well as add attributes and make it more ugrid compatible.

**Comment by kknee** [comment]
Most of the Rita runs are missing the std names for lat and lon

**Comment by drf5n** [comment]
It is unclear how they got onto Ike, but not Rita.  When I was editing the ncml files, I added the lat and lon variables by aggregating testbed.sura.org:/data/ftp/upload/Inundation/vims/selfe_tropical/runs/coords.nc file, (or a copy of it), which doesn't have the standard_name attribute.  I just added a file at testbed.sura.org:/data/ftp/upload/Inundation/vims/selfe_tropical/runs/coords_stdnames.nc with the standard names in it.

From https://github.com/ioos/comt_1_archive/blob/master/inundation_tropical/VIMS_SELFE/Hurricane_Ike_2D_final_run_with_waves/00_dir.ncml#L159 it looks like it refers to a file in the .../Output/ subdirectory that might need overwriting to match testbed.sura.org:/data/ftp/upload/Inundation/vims/selfe_tropical/runs/coords_stdnames.nc .   I'm not sure how to accomplish that.

**Comment by rsignell-usgs** [comment]
@drf5n, I looked on `comt.sura.org` and I can't find any 'coords_stdnames.nc' files, nor are there references to 'coords_stdnames.nc' files in the Ike aggregation ncml files. 

I do find lines in the Ike ncml that provide longitude/latitude `standard_name` however:
```
     <variable name="x" shape="node" type="float">
      <attribute name="standard_name" value="longitude"/>
      <attribute name="units" value="degrees_east"/>
     </variable>
```
I think that all that needs to be done is add the standard name to the Rita NcML files, the same as in these ones:
```
$ pwd
/data/comt_1_archive/inundation_tropical/VIMS_SELFE

$ find . -name '*.ncml' -exec grep -ls latitude {} \;
./Hurricane_Ike_3D_final_run_with_waves/00_dir.ncml
./Hurricane_Ike_2D_final_run_without_waves/00_dir.ncml
./Hurricane_Ike_2D_final_run_with_waves/00_dir.ncml
./Hurricane_Ike_3D_final_run_without_waves/00_dir.ncml
./Hurricane_Ike_2D_final_run_wave_only/00_dir.ncml
```
So just fix the ones on this list that aren't on the list above:
```
$ find . -name '*.ncml' -print
./Hurricane_Ike_3D_final_run_with_waves/00_dir.ncml
./Hurricane_Ike_2D_final_run_without_waves/00_dir.ncml
./Hurricane_Ike_2D_final_run_with_waves/00_dir.ncml
./Hurricane_Rita_3D_final_run_without_waves/Output/00_dir.ncml
./Hurricane_Rita_3D_final_run_without_waves/00_dir.ncml
./Hurricane_Rita_2D_final_run_without_waves/00_dir.ncml
./Hurricane_Rita_2D_final_run_with_waves/00_dir.ncml
./Hurricane_Rita_3D_final_run_with_waves/Output/00_dir.ncml
./Hurricane_Rita_3D_final_run_with_waves/00_dir.ncml
./Hurricane_Ike_3D_final_run_without_waves/00_dir.ncml
./Hurricane_Rita_2D_final_run_waves_only/00_dir.ncml
./Hurricane_Ike_2D_final_run_wave_only/00_dir.ncml
```
Do you agree?

**Comment by rsignell-usgs** [comment]
Awe heck, I can just add them.  Probably will take 5 min.  Let's see...

**Comment by rsignell-usgs** [comment]
Done!  I edited the files, and so as not to wait for the cron, reran the catalog generation script and restarted thredds:
```
 cd /home/testbed/comt_catalog/code
 python buildcatalog_comt1_archive.py
 sudo /etc/init.d/tomcat_thredds restart
```
It looks like the standard_names are now there for the Ike runs:
http://comt.sura.org/thredds/dodsC/data/comt_1_archive/inundation_tropical/VIMS_SELFE/Hurricane_Rita_2D_final_run_waves_only.html

**Comment by drf5n** [comment]
Thanks Rich.  I did the editing on the .ncml files way back when testbeddev.sura.org was current, and I haven't been following the maintenance or login access from there to testbed.sura.dev, comt, comt2 etc....    The newly updated .nc file was on the old server at testbed.sura.org:/data/ftp/upload/Inundation/vims/selfe_tropical/runs/coords_stdnames.nc and I was considering copying over the top of testbed.sura.org:/data/ftp/upload/Inundation/vims/selfe_tropical/runs/coords.nc which would have fixed anything on the old server that was aggregating that file explicitly, but certainly wouldn't have propagated into the current system.

**Comment by drf5n** [comment]
I did do the file copy on the testbed.sura.org. server and the standard_name attributes propagate to some of the files like http://testbedapps.sura.org/thredds/dodsC/alldata/Inundation/vims/selfe_tropical/runs/Ike/2D_varied_manning_windstress_with_wave/config_20121212/00_dir.ncml.html 

The iterative development I did on the old 00_dir.ncml files is awkward and admittedly inconsistent.  How are you managing the metadata maintenance of the ncml on the more recent servers?

**Comment by rsignell-usgs** [comment]
same as on the old server:
https://github.com/ioos/comt/wiki/COMT2%20Inventory%20and%20Upload%20Guidelines
 Just editing the 00_index.html files for anything that isn't being specified in the google doc.
